import Dimensions from "Dimensions";
import { Platform, StatusBar } from "react-native";
import LocalizedStrings from 'react-native-localization';
const strings = new LocalizedStrings({
	en:{
		home: 'Home',
		newsupdate: 'News Update',
		genealogy: 'Genealogy',
		mgntrade: 'MGN Trade',
		exchangemarket: 'Exchange Market',
		products: 'Products',
		ewallet: 'E-Wallet',
		report: 'Report',
		helpdesk: 'Helpdesk',
		myaccount: 'My Account',
		myaccountoverview: 'My Account Overview',
		cashpoint: 'CASH POINT',
		tradepoint: 'TRADE POINT',
		bonustradepoint: 'BONUS TRADE POINT',
		gamepoint: 'GAME POINT',
		achievedrank: 'Achieved Rank',
		name: 'Name',
		id: 'ID',
		investment: 'Investment',
		email: 'Email',
		sponsoredmembers: 'Sponsored Members',
		sponsoredbv: 'Sponsored BV',
		eprofitmaxcap: 'E-Profit Max Cap',
		sponsor: 'Sponsor',
		group: 'Group',
		registernewmember: 'Register New Member',
		addmessage: 'Add Message',
		subject: 'Subject',
		question: 'Question',
		accessplatform: 'Access Platform (MGN)',
		trade: 'Trade',
	},
	ch: {
		home: '主页',
		newsupdate: '最新公告',
		genealogy: '组织图',
		mgntrade: 'MGN交易平台',
		exchangemarket: '兑换市场',
		products: '产品',
		ewallet: '电子账户',
		report: '报告',
		helpdesk: '服务台',
		myaccount: '我的账户',
		myaccountoverview: '我的账户信息',
		cashpoint: '现金货币',
		tradepoint: '贸易货币',
		bonustradepoint: '红利贸易货币',
		gamepoint: '游戏货币',
		achievedrank: '取得级别',
		name: '名字',
		id: '账号',
		investment: '投资',
		email: '电子邮件',
		sponsoredmembers: '直推人数',
		sponsoredbv: '直推人BV',
		eprofitmaxcap: '最高盈利顶线',
		sponsor: '推荐图',
		group: '团队图',
		registernewmember: '注册新会员',
		addmessage: '添加留言',
		subject: '标题',
		question: '问题',
		accessplatform: '登入平台 (MGN)',
		trade: '交易平台',
	},
	ml: {
		home: 'Utama',
		newsupdate: 'Berita Terkini',
		genealogy: 'Genealogi',
		mgntrade: 'MGN Perdagangan',
		exchangemarket: 'Pasaran Pertukaran',
		products: 'Produk',
		ewallet: 'E-Wallet',
		report: 'Laporan',
		helpdesk: 'Perkhidmatan',
		myaccount: 'Akaun Saya',
		myaccountoverview: 'Maklumat Akaun',
		cashpoint: 'MATA WANG TUNAI',
		tradepoint: 'MATA WANG PERDAGANGAN',
		bonustradepoint: 'MATA WANG PERDAGANGAN BONUS',
		gamepoint: 'MATA WANG PERMAINAN',
		achievedrank: 'Kedudukan',
		name: 'Nama',
		id: 'ID',
		investment: 'Pelaburan',
		email: 'E-mel',
		sponsoredmembers: 'Ahli Menaja',
		sponsoredbv: 'Sponsored BV',
		eprofitmaxcap: 'E-Profit Max Cap',
		sponsor: 'Penaja',
		group: 'Kumpulan',
		registernewmember: 'Mendaftar Ahli Baru',
		addmessage: 'Tambah Mesej',
		subject: 'Subjek',
		question: 'Pertanyaan',
		accessplatform: 'Platform Access (MGN)',
		trade: 'Perdagangan',
	}
});

const window = Dimensions.get("window");

export default {
	// App Details
	appName: "Demo",

	// Window Dimensions
	windowHeight: window.height,
	windowWidth: window.width,

	// public variables

	// --- colors
	primaryColor: "#f9f9f9",

	// api
	apiUrl: 'http://amapi.ezymlm.net/',
	accessToken: "",

	//datas
	dashboard_data: [],
	news_data: [],
	bank_data: [],
	sponsor_data: [],
	group_data: [],
	global_string: strings,
};
